### PR TITLE
Miscellaneous improvements

### PR DESCRIPTION
**Pull request by justmoon**
### Create a `bin` script

Shorter, simpler command line for calling the module and cleaner package.json script integration.
### Fix console.log w/ parens

Lazy matching caused lines like this to get mangled:

``` js
console.log(example.toString())
// prints 'example'
```
### Comment out console.log statements

Test runs shouldn't spew all over the console unless the tests are failing. The assertion will print the value if it isn't what we expect.
### Fix rmdir crash

This was probably caused by some change upstream, but `readme-to-test` would simply crash for me with the following exception:

```
/opt/workspace/readme-to-test/node_modules/rmdir/lib/rmdir.js:80
                if (err) callback(err, _dirs, _files);
                         ^

TypeError: callback is not a function
    at Object._error (/opt/workspace/readme-to-test/node_modules/rmdir/lib/rmdir.js:80:26)
    at Object.Flow._run_series (/opt/workspace/readme-to-test/node_modules/node.flow/lib/flow.js:139:19)
    at Object.Flow._ready (/opt/workspace/readme-to-test/node_modules/node.flow/lib/flow.js:228:12)
    at /opt/workspace/readme-to-test/node_modules/node.flow/lib/flow.js:250:31
    at FSReqWrap.oncomplete (/opt/workspace/readme-to-test/node_modules/rmdir/lib/rmdir.js:72:23)
```
### Better formatted error messages

**Before:**

screenshot from 2016-02-15 14-12-40

_Pretty impossible to read, eh?_

**After:**

screenshot from 2016-02-15 14-12-57

_Ah, much nicer._
### Don't assume that user's code uses Babel 2015 preset

Since the tests were being generated in the user's module's directory, it was using the users `.babelrc`, which in my case did not contain the `es2015` preset and as such, I got the `Unknown keyword import` error.

By using `var ... = require(...)` we guarantee that the `assert` is loaded correctly in all versions of Node and all configurations of Babel.

### CODE REVIEW

**Comment by justmoon** [comment]
@aswitalski Ping!

**Comment by aswitalski** [comment]
Hey, sorry for missing your messages, I had a 3-month break from programming, will have a look at these things shortly... thx :)

**Comment by justmoon** [comment]
Awesome, thanks!

**Comment by aswitalski** [comment]
@justmoon Thx for your contribution

**Comment by justmoon** [comment]
Thanks for merging, could you also bump the version please?

**Pull request merged**
